Repository FRONTENDBOOTCAMP-14th/NETFLEX, pull requests merged in 2025-07, with the labels that each got.

#7 test : PR 테스트용
  README.md
Labels: ✋ Help wanted

#13 fix : 일정 컴포넌트 마크업 수정
  src/components/schedule/schedule.html
Labels: 🔨 Bugfix, 💻 feature

#17 feat : 에티켓 마크업 과 PR#16수정사항 반영
  src/components/etiquette/etiquette.css
  src/components/etiquette/etiquette.html
  src/components/etiquette/etiquette.js
Labels: 🔨 Bugfix, 💻 feature

#25 feat : 에티켓 마크업 수정과 css스타일 코드
  src/components/etiquette/etiquette.css
  src/components/etiquette/etiquette.html
  src/components/etiquette/etiquette.js
Labels: 🔨 Bugfix, 💻 feature, ✏️ Design

#28 feat : 에티켓 JS 작성
  src/components/etiquette/etiquette.css
  src/components/etiquette/etiquette.html
  src/components/etiquette/etiquette.js
Labels: 💻 feature, ✏️ Design

#33 feat : 지도 컴포넌트 사이드 메뉴 토글, 탭메뉴(검색 / 일정) 구현
  src/components/map/map.css
  src/components/map/map.html
  src/components/map/map.js
  src/styles/common/theme.css
Labels: 🔨 Bugfix, 💻 feature

#37 feat : 출국 전 체크리스트 컴포넌트 마크업 작성
  src/components/departure-checklist/departure-checklist.css
  src/components/departure-checklist/departure-checklist.html
  src/components/departure-checklist/departure-checklist.js
Labels: 💻 feature

#44 feat : 출국 전 체크리스트 컴포넌트 마크업 수정 및 코드 추가
  src/components/departure-checklist/departure-checklist.html
Labels: 🔨 Bugfix, 💻 feature

#48 feat : 출국 전 체크리스트 컴포넌트 스타일 코드 작성
  src/components/departure-checklist/checklist.json
  src/components/departure-checklist/departure-checklist.css
  src/components/departure-checklist/departure-checklist.html
Labels: ✏️ Design

#51 feat : 출국 전 체크리스트 JS 구현 (JSON 기반 렌더링 및 상태 저장)
  src/components/departure-checklist/checklist.json
  src/components/departure-checklist/departure-checklist.css
  src/components/departure-checklist/departure-checklist.html
  src/components/departure-checklist/departure-checklist.js
Labels: 💻 feature, ✏️ Design

#52 feat : 에티켓 json 추가와 호출
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/account/account.css
  src/components/account/account.html
  src/components/account/account.js
  src/components/etiquette/etiquette.css
  src/components/etiquette/etiquette.html
  src/components/etiquette/etiquette.js
Labels: 💻 feature

#53 feat : 출국 전 체크리스트 컴포넌트 css 반응형 코드 작성
  src/components/departure-checklist/departure-checklist.css
Labels: ✏️ Design

#56 init : prettier 파일 생성
  .prettierrc
  package-lock.json
  package.json
  src/components/departure-checklist/departure-checklist.css
Labels: 🟠 Priorty : High

#62 refactor : CSS 디버깅, 포맷팅 수정
  package.json
  src/components/map/map.css
  src/components/map/map.html
  src/components/map/map.js
Labels: 🔨 Bugfix, ✏️ Design

#65 feat : 에티켓 카드 반응형 구현
  src/components/etiquette/etiquette-data.json
  src/components/etiquette/etiquette.css
  src/components/etiquette/etiquette.html
  src/components/etiquette/etiquette.js
Labels: 💻 feature

#69 docs : assets 이미지 폴더 수정과 이미지 추가
  src/assets/images/etiquette/JP/etiquette-jp-1_1x.png
  src/assets/images/etiquette/JP/etiquette-jp-1_1x.webp
  src/assets/images/etiquette/JP/etiquette-jp-1_2x.png
  src/assets/images/etiquette/JP/etiquette-jp-1_2x.webp
  src/assets/images/etiquette/JP/etiquette-jp-2_1x.png
  src/assets/images/etiquette/JP/etiquette-jp-2_1x.webp
  src/assets/images/etiquette/JP/etiquette-jp-2_2x.png
  src/assets/images/etiquette/JP/etiquette-jp-2_2x.webp
  src/assets/images/etiquette/JP/etiquette-jp-3_1x.png
  src/assets/images/etiquette/JP/etiquette-jp-3_1x.webp
  src/assets/images/etiquette/JP/etiquette-jp-3_2x.png
  src/assets/images/etiquette/JP/etiquette-jp-3_2x.webp
  src/assets/images/etiquette/JP/etiquette-jp-4_1x.png
  src/assets/images/etiquette/JP/etiquette-jp-4_1x.webp
  src/assets/images/etiquette/JP/etiquette-jp-4_2x.png
  src/assets/images/etiquette/JP/etiquette-jp-4_2x.webp
  src/assets/images/etiquette/UK/etiquette-london-1_1x.avif
  src/assets/images/etiquette/UK/etiquette-london-1_1x.png
  src/assets/images/etiquette/UK/etiquette-london-1_1x.webp
  src/assets/images/etiquette/UK/etiquette-london-1_2x.avif
  src/assets/images/etiquette/UK/etiquette-london-1_2x.png
  src/assets/images/etiquette/UK/etiquette-london-1_2x.webp
  src/assets/images/etiquette/UK/etiquette-london-2_1x.avif
  src/assets/images/etiquette/UK/etiquette-london-2_1x.png
  src/assets/images/etiquette/UK/etiquette-london-2_1x.webp
  src/assets/images/etiquette/UK/etiquette-london-2_2x .avif
  src/assets/images/etiquette/UK/etiquette-london-2_2x.png
  src/assets/images/etiquette/UK/etiquette-london-2_2x.webp
  src/assets/images/etiquette/UK/etiquette-london-3_1x .avif
  src/assets/images/etiquette/UK/etiquette-london-3_1x.png
  src/assets/images/etiquette/UK/etiquette-london-3_1x.webp
  src/assets/images/etiquette/UK/etiquette-london-3_2x.avif
  src/assets/images/etiquette/UK/etiquette-london-3_2x.png
  src/assets/images/etiquette/UK/etiquette-london-3_2x.webp
  src/assets/images/etiquette/UK/etiquette-london-4_1x.avif
  src/assets/images/etiquette/UK/etiquette-london-4_1x.png
  src/assets/images/etiquette/UK/etiquette-london-4_1x.webp
  src/assets/images/etiquette/UK/etiquette-london-4_2x.avif
  src/assets/images/etiquette/UK/etiquette-london-4_2x.png
  src/assets/images/etiquette/UK/etiquette-london-4_2x.webp
Labels: ✏️ Design

#72 feat : 환율 컴포넌트 구현, 나라별 svg 이름 변경
  package.json
  src/assets/svg/eu.svg
  src/assets/svg/jp.svg
  src/assets/svg/uk.svg
  src/assets/svg/us.svg
  src/components/exchange-rate/exchange-rate.css
  src/components/exchange-rate/exchange-rate.html
  src/components/exchange-rate/exchange-rate.js
Labels: 💻 feature

#75 feat : 가계부 마크업
  src/components/account/account.css
  src/components/account/account.html
Labels: 💻 feature

#78 feat : 일정 페이지 마크업 수정 & 스타일 코드 수정 및 모달 코드 추가 & JS 구현
  src/pages/schedule-page/schedule-page.css
  src/pages/schedule-page/schedule-page.html
  src/pages/schedule-page/schedule-page.js
  src/pages/schedule-page/schedule.js
  src/pages/utils/modal.js
Labels: 💻 feature, ✏️ Design

#81 feat : 헤더 컴포넌트 생성 및 index.html에 호출
  index.html
  public/favicon32x.png
  src/components/navigation/navigation.css
  src/components/navigation/navigation.html
  src/components/navigation/navigation.js
  src/js/main.js
  src/js/utils/header_component.js
Labels: 💻 feature, ✏️ Design

#90 feat : 일정 등록 페이지 마크업 코드 작성
  src/pages/schedule-page/schedule-page.js
  src/pages/schedule-register/schedule-register.css
  src/pages/schedule-register/schedule-register.html
  src/pages/schedule-register/schedule-register.js
Labels: 💻 feature

#94 refactor : 날씨 svg 경로 수정 (public으로 변경)
  public/svg/cloudy-01.svg
  public/svg/cloudy-03.svg
  public/svg/cloudy.svg
  public/svg/rain-01.svg
  public/svg/rain-02.svg
  public/svg/rain-03.svg
  public/svg/snow.svg
  public/svg/sunny.svg
  public/svg/thunder.svg
  src/components/weather/weather.js
Labels: 🔨 Bugfix
